app/Ldap/User.php, composer.json, composer.lock, database/migrations/2019_02_28_134322_set-email-to-null.php
=> Adiciona user com email nulo.

resources/views/ldapusers/show.blade.php
=> Fix #45 - Corrigido ternário conforme php7

app/Jobs/SincronizaReplicado.php
=> Fix #42 - Trazer o nompesttd devido ao nome social

app/Jobs/SincronizaReplicado.php, app/Ldap/Group.php, app/Ldap/User.php, composer.lock, resources/views/ldapusers/sync.blade.php
Usando dois métodos novos do replicado vinculos e ativos por vinculo
=> Fix #43 - Sincronizando outros tipos de vínculo

composer.lock, config/laravel-usp-theme.php
=> Fix #48 - Corrigida rota para logout

app/Http/Controllers/Auth/LoginController.php, app/Jobs/SincronizaReplicado.php, app/Ldap/Group.php, app/Ldap/User.php
=> Fix #51 - Sincronizando e criando grupos com o tipvinext e adionado o departamento na conta

app/Ldap/User.php, resources/views/ldapusers/sync.blade.php
=> Fix #54 - Senha incial e trocar senha no primeiro logon

app/Ldap/User.php
=> Fix #57 - Só ativar a conta quando for conta nova

composer.json, composer.lock, resources/views/configs/edit.blade.php, resources/views/index.blade.php, resources/views/ldapusers/create.blade.php, resources/views/ldapusers/index.blade.php, resources/views/ldapusers/show.blade.php, resources/views/ldapusers/solicita-admin.blade.php, resources/views/ldapusers/sync.blade.php, resources/views/master.blade.php, resources/views/vendor/laravel-usp-theme/master.blade.php
=> Fix #55 - Override no uspdev/laravel-usp-theme para utilizar select2/select2

app/Http/Controllers/LdapUserController.php
=> Fix #61 - Corrigida a busca com dois ou mais grupos

resources/views/ldapusers/index.blade.php, resources/views/ldapusers/nav.blade.php
=> Fix #64 - Paginação e filtros ok

app/Http/Controllers/Auth/LoginController.php, app/Jobs/SincronizaReplicado.php
=> Fix #66 - Melhorada a nomenclatura dos grpuos

.env.example, app/Jobs/SincronizaReplicado.php, app/Ldap/Group.php, app/Ldap/User.php, config/web-ldap-admin.php
=> Fix #21 - Remove desligaos dos grupos, insere no grupo Desativados e desativa a conta

app/Ldap/User.php, resources/views/ldapusers/show.blade.php
=> Fix #71 - Adicionada informação Department em Minha conta

app/Jobs/SincronizaReplicado.php, app/Ldap/User.php, resources/views/ldapusers/show.blade.php, resources/views/ldapusers/sync.blade.php
=> Fix #72 - Adicionado Docente Aposentado na sincronização

app/Http/Controllers/Auth/LoginController.php, app/Jobs/SincronizaReplicado.php, app/Ldap/User.php, resources/views/ldapusers/show.blade.php, resources/views/ldapusers/sync.blade.php
=> Fix #74 - Ao sincronizar alunos de Graduação subdividir os grupos por departamento de ensino

composer.lock
=> Fix #78 - Fix Security Alerts

.env.example
=> Fix #81 - Adicionado ao .env.example as configurações do SGBD replicado

composer.lock
Fix #80 
composer update uspdev/replicado
=> Fix #80 - Incluso Aluno de convênio intercâmbio graduação na sincronização

.gitignore, app/Jobs/SincronizaReplicado.php, app/Ldap/Group.php, app/Ldap/User.php, resources/views/ldapusers/index.blade.php
=> Fix #75 - Corrigido na sincronização adicionar usuários nos grupos em que pertence

app/Http/Controllers/Auth/LoginController.php, app/Jobs/SincronizaReplicado.php, composer.lock, resources/views/ldapusers/sync.blade.php
=> Fix #101 - Atualizado para novo release do uspdev/replicado

.gitignore, resources/views/solicita/create.blade.php
=> Fix #113 - Corrigida a rota para solicitação de conta de administrador

.env.example, config/laravel-usp-theme.php
=> Fix #111 - Solicitação de conta de administrador opcional no .env

.env.example, app/Http/Controllers/LdapUserController.php, app/Http/Controllers/SolicitaController.php
Fix #118
Adicionado no .env.example a variavel do skin laravel-usp-theme
=> Fix #118 - Alterado gate logado para gate user

resources/lang/vendor/laravel-usp-theme/pt-br/laravel-usp-theme.php, resources/views/index.blade.php
=> Fix #120 - Ajustando o title para app.name

app/Ldap/User.php
=> filtrando busca somente para users

.env.example, app/Http/Controllers/LdapUserController.php, composer.json, composer.lock, config/web-ldap-admin.php, resources/views/ldapusers/partials/show-basic.blade.php
Fix #128 
Require uspdev/wsfoto
Parametrizado o uso do wsfoto
Adicionada a informação no .env.example
Adicionada string foto no controller LdapUser
Exibindo a foto na view show-basic
=> Fix 128 - Mostrando a foto

.env.example, .gitignore, README.md, app/Http/Controllers/LdapUserController.php, app/Ldap/User.php, composer.lock, config/web-ldap-admin.php, resources/views/ldapusers/partials/show-basic.blade.php
Fix #135 
Usando json com os possíveis código do curso, código da habilitação e nome abreviado do setor.
Quando não se utiliza o json o métdodo Graduacao::setorAluno será utilizado, porém esse método retorna o setor do coordenador do curso que pode ser diferente do setor ou departamento de ensino do aluno de graduação
=> Parametrizando o setor do aluno de graduação

.env.example, app/Http/Controllers/LdapUserController.php, app/Ldap/Group.php, config/web-ldap-admin.php, resources/views/ldapusers/partials/create-form.blade.php, resources/views/ldapusers/partials/show-pwd-form.blade.php
Fix #138 
Parametrizada a mensagem de complexidade de senha
Inclusão de variável para foto fake customizada
Ao criar usuário trazendo os grupos existentes e também aceita grupos novos
=> Informando a complexidade de senha

.env.example, resources/views/configs/edit.blade.php
=> Grupos fixos e pessoas sem vínculo

app/Http/Controllers/LdapUserController.php, resources/views/ldapusers/partials/add-group-form.blade.php, resources/views/ldapusers/partials/show-basic.blade.php, resources/views/ldapusers/show.blade.php, routes/web.php
=> Adicionando usuário ao(s) grupo(s)

resources/views/ldapusers/partials/show-basic.blade.php, resources/views/ldapusers/show.blade.php
Mudando a foto para o lado direito.
=> Posicao foto
